GET https://f84fuz51qf.execute-api.eu-west-1.amazonaws.com/Prod/get-todos

Accept: application/json

###

GET https://f84fuz51qf.execute-api.eu-west-1.amazonaws.com/Prod/get-todo/jjjjj

Accept: application/json